[package]
name = "ek-logic"
version = "0.1.0"
description = "Ego-Kernel On-Chain Program: Reputation Ledger + Micro-Escrow"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "ek_logic"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { version = "0.31.0", features = ["init-if-needed"] }
